### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [Morcu/Qiskit_Hands-on-lab#1]
I recently came across your project Qiskit_Hands-on-lab and I noticed that the repository github.com/Morcu/Qiskit_Hands-on-lab currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by Morcu** [comment]
Thanks for bringing this to my attention! I've added the Apache 2.0 license to the repository as you suggested. I really appreciate your feedback and hope this helps clarify the open-source nature of the project.

Let me know if you have any further suggestions!

**Comment by cbjuan** [comment]
Thanks!
